### ISSUE TITLE
Insight default colors to DASH blue

### ISSUE THREAD

**Issue by CryptoTeller** [dashpay/insight-ui-dash#1]
can we update main.min.css with DASH colors?

**Comment by snogcel** [comment]
The best place to edit that would be: https://github.com/dashpay/insight-ui-dash/blob/master/public/src/css/common.css. If you update the default colors please submit a Pull Request :-)

**Comment by CryptoTeller** [comment]
thanks I submitted a pull for these colors
replace title bar 8dc429 (light Green) with DASH Official Blue 1c75bc
replace search bar bkg 7cad23(green) with 1763a0 Slightly Darker Official Blue
replace status 597338 with 263e74 Deep Blue

**Comment by snogcel** [comment]
Thanks for suggesting this! We've taken a full sweep on this updating not only the colors but also some images with https://github.com/dashpay/insight-ui-dash/pull/5, closing out issue :-)
