### ISSUE TITLE
bitcore-node-dash Installation error

### ISSUE THREAD

**Issue by afzydev** [dashpay/insight-ui-dash#10]
Hi

Please help me.
Whenever i am installing bitcore-node-dash i am getting this error.
```

bitcore-node-dash@3.0.5 preinstall /home/afzal/.nvm/versions/node/v4.8.4/lib/node_modules/bitcore-node-dash
> ./scripts/download

sh: 1: ./scripts/download: Permission denied
npm ERR! Linux 3.16.0-30-generic
npm ERR! argv "/home/afzal/.nvm/versions/node/v4.8.4/bin/node" "/home/afzal/.nvm/versions/node/v4.8.4/bin/npm" "install" "-g" "bitcore-node-dash"
npm ERR! node v4.8.4
npm ERR! npm  v2.15.11
npm ERR! code ELIFECYCLE

npm ERR! bitcore-node-dash@3.0.5 preinstall: `./scripts/download`
npm ERR! Exit status 126
npm ERR! 
npm ERR! Failed at the bitcore-node-dash@3.0.5 preinstall script './scripts/download'.
npm ERR! This is most likely a problem with the bitcore-node-dash package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ./scripts/download
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs bitcore-node-dash
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls bitcore-node-dash
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/afzal/npm-debug.log
```

**Comment by Alex-Werner** [comment]
Hello @afzydev 
I suggest you to follow this, an easier way to install it : https://gist.github.com/Alex-Werner/6de16b72a9070d945e3e74691d318f24
Also, here you have a permission issue which is not related to the package but with user rights.

**Comment by afzydev** [comment]
Hi @Alex-Werner 

Thanks you are great.

Please let me check and let and you know.

**Comment by afzydev** [comment]
Hi @Alex-Werner 

What is meant by this line. ?
Create dash.conf file in .dashcore with data allowing to be requested by RPC ?

Thanks

**Comment by afzydev** [comment]
Hi @Alex-Werner 

Thanks i got the dashcore and successfully able to setup the dash.

The only problem is when i am copying file in  dash.conf and running .bin/dashd
following error occurs.

Please help me to setup .I am lost :( 

> dashd: zmq/zmqpublishnotifier.cpp:100: virtual void CZMQAbstractPublishNotifier::Shutdown(): Assertion `psocket' failed.
> Aborted (core dumped)

**Comment by Alex-Werner** [comment]
@afzydev Where are you copying the file dash.conf ? Did you modified it (ports) ? 
Also what is your operating system ? 
Can you describe how did you installed it (dashd) ?

**Comment by afzydev** [comment]
@Alex-Werner 

Thanks for replying.

I am working on Ubuntu .

I have install dashcore and  created dash.conf file in .dashcore folder and updated file with the example given like : 

```
server=1
whitelist=0.0.0.0/0
txindex=1
addressindex=1
timestampindex=1
spentindex=1
zmqpubrawtx=tcp://127.0.0.1:28332
zmqpubrawtxlock=tcp://127.0.0.1:28332
zmqpubhashblock=tcp://127.0.0.1:28332
rpcuser=dash
rpcpassword=local321
rpcport=9998
rpcallowip=0.0.0.0/0
uacomment=bitcore
debug=1
```
And when i am opening dash core UI like described in https://dashpay.atlassian.net/wiki/spaces/DOC/pages/1867930/Dash+Core+Wallet+for+Linux 

My synchronization is failing.

Please explain everything in short as I am ver new to dash and need to implement in one my site.
I am in a big problem as my performances are getting affected.

Thanks

**Comment by afzydev** [comment]
@Alex-Werner 
Hi Alex

You are awesome .Dashcore is now running successfully and synchronization is also done.
I have few tasks in dash, can you please tell me if these tasks will be done by using this API or not.

1.generate new address
2.get balance
3.send dash to any other address i.e perform transactions.

Thanks

**Comment by Alex-Werner** [comment]
1) Seems better for me to use https://github.com/dashevo/bitcore-lib-dash for generating a new address
2) You can get balance using the api : `/insight-api-dash/addr/${theAddr}`
3) Broadcast either standard transaction (send rawtx to : `/insight-api-dash/tx/send`) or instantSend transaction (send rawtx to `insight-api-dash/tx/sendix`.

**Comment by afzydev** [comment]
Thanks @Alex-Werner 

Really cool !

One thing more please

Need to track all transactions and capturing transactions for those addresses which are used by my wallet.?

Thanks

**Comment by Alex-Werner** [comment]
Then you might want to read the documentation ;) 

1) Using websocket : https://github.com/dashevo/insight-api-dash#web-socket-api 
2) By pulling data in REST (I don't advice that for your specific case...)

**Comment by afzydev** [comment]
@Alex-Werner 
Thanks .

Should I install this repo **https://github.com/dashevo/bitcore-lib-dash** inside  **insight-api-dash** ?

**Comment by Alex-Werner** [comment]
I've made this so it's easier to understand : https://medium.com/@obusco/setup-instant-send-transaction-the-comprehensive-way-a80a8a0572e 

Using npm install insight-api-dash will directly use the good repository. 
But if you prefer to git clone, then yes, it's on dashevo repo

**Comment by afzydev** [comment]
@Alex-Werner 

I am not able to generate new address using insight-ui-dash api.Please guide me how to generate new addresses.

Thanks

**Comment by Alex-Werner** [comment]
Hi @afzydev, 
This is not related to insight-ui-dash. There is not generateNewAddress functionnality in the UI version of the explorer.

**Comment by afzydev** [comment]
@Alex-Werner i need to generate addresses.Can you please tell me how shall i implement it .

**Comment by UdjinM6** [comment]
Github issue tracker is not a support forum and you guys already discussed way too many topics here - original issue was solved like a month ago.

Locking it.
