### ISSUE TITLE
Merchant panel

### ISSUE THREAD

**Issue by Serrenima** [dashpay/insight-ui-dash#11]
UI nice, but how I can see and control my wallet information (see transactions, address, do received...) with web?

Thanks.

**Comment by nmarley** [comment]
Insight is just a blockchain explorer and has no wallet-related functionality. The search box will find transactions, addresses, blocks and block height, and will display all of these with links to the relevant related other objects, e.g. a block listing will show TXes contained, a specific TX page will have links to the addresses.
