### ISSUE TITLE
RPC bad connection broke insight

### ISSUE THREAD

**Issue by Serrenima** [dashpay/insight-ui-dash#12]
Hi all,
When I try to coonect RPC with bad Port, **:3001/insight** is can't open page, dash core is work, because gen. address.
Any ideas?
Because if bad guys try to connect with my IP and incorrectly port, they down insight.

Thanks

**Comment by nmarley** [comment]
Hi, generally it's recommended to only open your JSONRPC port to localhost, and many times the app port (3001 in this case) is placed behind nginx or a load balancer.

I'm not sure what else your question is about, I don't quite understand what you are trying to say. But in general, only allow Insight to access DashCore on localhost and use proper security for your web server, make sure you restrict ports.
