### ISSUE TITLE
Navbar layout breaks in Japanese and German

### ISSUE THREAD

**Issue by tagawa** [dashpay/insight-ui-dash#7]
## Steps to reproduce:
1. Go to https://dashcore.info/
2. In the language list in the footer, click "Japanese" or "Deutsch".

## What should happen:
The top navbar should remain on one line.

## What actually happens:
The navbar breaks onto two lines between the search and status boxes.

<img width="600" alt="dash-ja-broken" src="https://user-images.githubusercontent.com/94173/27172260-8de57b82-51ef-11e7-9841-a3f70ca371b1.png">

<img width="512" alt="dash-de-broken" src="https://user-images.githubusercontent.com/94173/27172263-912be920-51ef-11e7-8bce-b4007a8e1565.png">

**Comment by Alex-Werner** [comment]
Merged in https://github.com/dashevo/insight-ui-dash/pull/2
Thanks !
