### ISSUE TITLE
bitcore-node-dash start error

### ISSUE THREAD

**Issue by bsbits** [dashpay/insight-ui-dash#9]
Hello, 

So I have set everything properly, I launched 2 insight versions for BTC and LTC.
All required libraries, dependencies are met, when I start the node, I get this error.

`bitcore-node-dash start`
```
[2017-07-14T16:29:27.544Z] info: Using config: /home/ubuntu/insight/bitcore-node-dash.json
[2017-07-14T16:29:27.545Z] info: Using network: livenet
[2017-07-14T16:29:27.546Z] info: Starting bitcoind
[2017-07-14T16:29:27.548Z] info: Using bitcoin config file: /home/ubuntu/insight/data/dash.conf
[2017-07-14T16:29:27.551Z] info: Starting dash process
[2017-07-14T16:29:27.561Z] error: Error: spawn /home/ubuntu/.nvm/versions/node/v4.8.4/lib/node_modules/bitcore-node-dash/lib/scaffold/data/dashd ENOENT
    at exports._errnoException (util.js:907:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:189:32)
    at onErrorNT (internal/child_process.js:363:16)
    at nextTickCallbackWith2Args (node.js:511:9)
    at process._tickCallback (node.js:425:17)
```

**Comment by Alex-Werner** [comment]
Hello @bsbits, 

I can assume from logs provided that you run on Ubuntu, right ? 
Could you provide more information about how you install it in the first place ?

**Comment by bsbits** [comment]
Correct, and this is the process I used to install it.
First, I created an aws instance.

`sudo apt-get update -y`
`sudo apt-get upgrade`

`curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.2/install.sh | bash`
`export NVM_DIR="$HOME/.nvm"`
`[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh" # This loads nvm`

`
nvm install v4`

```
npm install -g bitcore-node-dash
bitcore-node-dash create mynode
cd mynode
bitcore-node-dash install insight-api-dash
bitcore-node-dash install insight-ui-dash
bitcore-node-dash start

```

**Comment by bsbits** [comment]
Oh, and I also had to install python.

`sudo apt-get install python`

without it, I can not run `npm install -g bitcore-node-dash `without errors

**Comment by Alex-Werner** [comment]
Did you remember or have any log of the error regarding Python ? 

When you did the creation of the mynode, are you sure that the folder mynode exist ? (as you diverted here a little from the doc).

**Comment by bsbits** [comment]
Python is required for zmq@2.15.3 

So I had to install python and node-gyp

The folder mynode exists, I had to cd there to install the api and ui.

The doc here is not complete, Insight require node js to run.

**Comment by Alex-Werner** [comment]
Yeah, actually the doc is here : https://github.com/dashpay/bitcore-node-dash 
As this place is for Insight-ui (which is only an Angular Plugin allowing to explore the Blockchain). 

But nevertheless, there is still an issue. During the time I move forward on my end, could you perform a search for the file `dashd`

**Comment by bsbits** [comment]
/home/ubuntu/.bitcore/data/dashcore-0.12.1/bin/dashd
/home/ubuntu/.bitcore/data/dashd

**Comment by Alex-Werner** [comment]
Can I propose you to follow this : https://gist.github.com/Alex-Werner/0be9bb4757b013043eeb9be5d93d9d39

**Comment by bsbits** [comment]
worked like a charm.

**Comment by afzydev** [comment]
Hi

Please help me.
Whenever i am installing bitcore-node-dash i am getting this error.

```
bitcore-node-dash@3.0.5 preinstall /home/afzal/.nvm/versions/node/v4.8.4/lib/node_modules/bitcore-node-dash
> ./scripts/download

sh: 1: ./scripts/download: Permission denied
npm ERR! Linux 3.16.0-30-generic
npm ERR! argv "/home/afzal/.nvm/versions/node/v4.8.4/bin/node" "/home/afzal/.nvm/versions/node/v4.8.4/bin/npm" "install" "-g" "bitcore-node-dash"
npm ERR! node v4.8.4
npm ERR! npm  v2.15.11
npm ERR! code ELIFECYCLE

npm ERR! bitcore-node-dash@3.0.5 preinstall: `./scripts/download`
npm ERR! Exit status 126
npm ERR! 
npm ERR! Failed at the bitcore-node-dash@3.0.5 preinstall script './scripts/download'.
npm ERR! This is most likely a problem with the bitcore-node-dash package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ./scripts/download
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs bitcore-node-dash
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls bitcore-node-dash
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/afzal/npm-debug.log
```
Thanks

**Comment by Alex-Werner** [comment]
Hello @afzydev 
I suggest you to follow this, an easier way to install it : https://gist.github.com/Alex-Werner/6de16b72a9070d945e3e74691d318f24
Also, here you have a permission issue which is not related to the package but with user rights.
